### ISSUE TITLE
can't use skpm with sketch-plugin-log :D

### ISSUE THREAD

**Issue by lifeiscontent** [sketch-plugin-development/sketch-plugin-log#1]

**Comment by zschuessler** [comment]
Hey! Thanks for taking the time to open an issue. Not sure what this means, could you provide more info on your use case and suggestions? :smile:

**Comment by lifeiscontent** [comment]
@zschuessler there's a sketch tool to build and publish sketch plugins. I'd be interested to see if you could get this to work with it.

https://github.com/skpm/skpm

**Comment by lifeiscontent** [comment]
@zschuessler actually, I just realized they have a built in logger. so... nvm
